language: python

python:
- 3.7

dist: xenial

sudo: true

services:
- mysql

install:
- pip install --upgrade pip
- pip install flake8 coveralls tox-travis

before_script:
- flake8 django_crypto_fields
- mysql -e 'create database edc character set utf8;'

script:
- coverage run setup.py test

after_success:
- coveralls
